//! The box tree: one [`LayoutBox`] per generated CSS box, built from a
//! [`cl_style::StyledDocument`] by [`build`].
//!
//! Box generation here follows CSS 2.1 §9.2 at the level M1a's scope needs: an element with
//! `display: none` (and its whole subtree) generates no box at all; every other element
//! generates a `Block` or `Inline` box per its (already-folded, see
//! [`crate::style_adapt::adapt`]) computed `display`; a text node generates an `InlineText`
//! box; `<br>` generates a `LineBreak` box; and a block container whose children mix
//! block-level and inline-level boxes gets each maximal run of inline-level children wrapped
//! in a single anonymous block box (CSS 2.1 §9.2.1.1), so the container ends up with only
//! block-level children.
//!
//! [`build`] walks the DOM with an explicit stack rather than recursion, for the same reason
//! every traversal elsewhere in `ChromeLight` does: a document's nesting depth is
//! attacker-controlled, and a recursive walk would let a hostile document overflow the call
//! stack.

use cl_dom::{Document, NodeId, NodeKind, local_name};
use cl_style::StyledDocument;

use crate::geom::{Display, LayoutStyle};
use crate::style_adapt::adapt;

/// The id of one [`LayoutBox`] in a [`BoxTree`].
///
/// Mirrors `cl_dom::NodeId`: an index into [`BoxTree`]'s internal arena, meaningful only
/// relative to the tree that produced it, saturating rather than panicking if somehow more
/// than `u32::MAX` boxes were ever built.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct BoxId(u32);

impl BoxId {
    /// Builds a `BoxId` from a raw arena index, saturating to `u32::MAX` (never assigned to a
    /// real box by [`BoxTree`]'s builder) rather than panicking if `index` does not fit in a
    /// `u32`.
    #[must_use]
    fn from_index(index: usize) -> Self {
        Self(u32::try_from(index).unwrap_or(u32::MAX))
    }

    /// Returns the raw arena index this id names.
    #[must_use]
    pub fn index(self) -> usize {
        self.0 as usize
    }
}

/// What kind of CSS box a [`LayoutBox`] is.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum BoxKind {
    /// A block-level box generated by an element (`display: block`, after
    /// [`crate::style_adapt::adapt`]'s fold).
    Block,
    /// An inline-level box generated by an element (`display: inline`).
    Inline,
    /// The box generated by a text node: `LayoutBox::node` names the same
    /// [`cl_dom::NodeId`] redundantly, so a caller that only has a `BoxKind::InlineText`
    /// pattern match (not the enclosing `LayoutBox`) still has the node id in hand.
    InlineText(cl_dom::NodeId),
    /// An anonymous block box [`build`] synthesizes to wrap a run of inline-level children
    /// when a block container's children are a mix of block-level and inline-level boxes
    /// (CSS 2.1 §9.2.1.1). Has no [`cl_dom::NodeId`] of its own — `LayoutBox::node` is
    /// `None`.
    AnonymousBlock,
    /// An anonymous inline box. Not generated by [`build`] in M1a (there is no construction
    /// rule in this task's scope that needs one); kept in the enum so a later task can
    /// introduce one without an API break.
    AnonymousInline,
    /// The box generated by a `<br>` element: forces a line break wherever it falls in
    /// inline content, and lays out no content of its own.
    LineBreak,
}

/// One generated CSS box.
#[derive(Debug, Clone, PartialEq)]
pub struct LayoutBox {
    /// The DOM node this box was generated for, or `None` for a box [`build`] synthesized
    /// (an anonymous block, or the empty fallback root for a document with no root element).
    pub node: Option<cl_dom::NodeId>,
    /// What kind of box this is.
    pub kind: BoxKind,
    /// This box's layout-relevant computed style.
    pub style: LayoutStyle,
    /// This box's children, in box (≈ document) order.
    pub children: Vec<BoxId>,
}

/// The tree of generated CSS boxes for one document.
#[derive(Debug, Clone)]
pub struct BoxTree {
    boxes: Vec<LayoutBox>,
    /// The id of the tree's root box (the box generated for the document's root element, or
    /// a synthetic empty box for a document with none).
    pub root: BoxId,
}

impl BoxTree {
    /// Looks up a box by id. `None` if `id` is out of range (it cannot be "from another
    /// tree" the way `cl_dom::NodeId` can be from another document — `BoxId` is not `Copy`
    /// across trees in any API this crate exposes today, but the check costs nothing and
    /// keeps this total the same way `Document::get` is).
    #[must_use]
    pub fn get(&self, id: BoxId) -> Option<&LayoutBox> {
        self.boxes.get(id.index())
    }

    /// The number of boxes in the tree.
    #[must_use]
    pub fn len(&self) -> usize {
        self.boxes.len()
    }

    /// Whether the tree has no boxes at all. [`build`] always produces at least the root
    /// box, so this is always `false` in practice; provided for API symmetry with
    /// [`BoxTree::len`] (clippy's `len_without_is_empty`).
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.boxes.is_empty()
    }
}

/// Builds the box tree for `doc`.
///
/// Total over any [`StyledDocument`]: a document with no root element produces a `BoxTree`
/// whose root is a single, childless, styleless (`LayoutStyle::initial()`) anonymous block —
/// there is no element to generate a real box from, but [`BoxTree::root`] must still name a
/// valid box. See the module docs for the box-generation rules, and
/// [`crate::style_adapt::adapt`] for how a `ComputedValues` becomes a [`LayoutStyle`].
#[must_use]
pub fn build(doc: &StyledDocument) -> BoxTree {
    let document = doc.document();
    let mut boxes: Vec<LayoutBox> = Vec::new();

    let Some(root_node) = root_element(document) else {
        let root = push_box(&mut boxes, None, BoxKind::AnonymousBlock, LayoutStyle::initial(), Vec::new());
        return BoxTree { boxes, root };
    };

    let root_style = doc
        .computed(root_node)
        .map(adapt)
        .unwrap_or_else(LayoutStyle::initial);
    if root_style.display == Display::None {
        // The document element itself is `display: none` (unusual, but not impossible —
        // e.g. an author stylesheet with `html { display: none }`): the whole document
        // generates no box, exactly as `classify_child` would treat any other `display:
        // none` element. Same synthetic-empty-tree fallback as "no root element at all".
        let root = push_box(
            &mut boxes,
            None,
            BoxKind::AnonymousBlock,
            LayoutStyle::initial(),
            Vec::new(),
        );
        return BoxTree { boxes, root };
    }
    let root_kind = container_kind(&root_style);

    let mut stack: Vec<Frame> = vec![Frame {
        node: root_node,
        style: root_style,
        kind: root_kind,
        children: document.children(root_node).collect(),
        next_child: 0,
        built: Vec::new(),
    }];

    loop {
        let Some(top) = stack.len().checked_sub(1) else {
            break;
        };
        let next_child = stack[top].children.get(stack[top].next_child).copied();
        stack[top].next_child += 1;

        let Some(child_id) = next_child else {
            // This frame's children are exhausted: finalize its box and hand it to the
            // parent frame (or, if this was the root frame, return it as the tree's root).
            let frame = stack.pop().unwrap_or_else(|| {
                // Unreachable in practice — `top` was just computed as a valid index into a
                // non-empty `stack` — but written without `expect`/`unwrap` panicking on a
                // real failure: falls back to an empty frame rather than aborting.
                Frame {
                    node: root_node,
                    style: LayoutStyle::initial(),
                    kind: ContainerKind::Block,
                    children: Vec::new(),
                    next_child: 0,
                    built: Vec::new(),
                }
            });
            let children = wrap_inline_runs(&mut boxes, frame.built, &frame.style);
            let kind = match frame.kind {
                ContainerKind::Block => BoxKind::Block,
                ContainerKind::Inline => BoxKind::Inline,
            };
            let box_id = push_box(&mut boxes, Some(frame.node), kind, frame.style, children);
            match stack.last_mut() {
                Some(parent) => parent.built.push(box_id),
                None => return BoxTree { boxes, root: box_id },
            }
            continue;
        };

        match classify_child(doc, child_id, &stack[top].style) {
            ChildBox::Skip => {}
            ChildBox::Leaf(kind, style) => {
                let box_id = push_box(&mut boxes, Some(child_id), kind, style, Vec::new());
                stack[top].built.push(box_id);
            }
            ChildBox::Container(kind, style) => {
                stack.push(Frame {
                    node: child_id,
                    style,
                    kind,
                    children: document.children(child_id).collect(),
                    next_child: 0,
                    built: Vec::new(),
                });
            }
        }
    }

    // Unreachable in practice (every path above either loops or returns — see the loop body:
    // the only `break` is the defensive `checked_sub` guard, which cannot fire because the
    // stack starts non-empty and every `pop` is immediately followed by either pushing to the
    // now-topmost frame or returning). Kept panic-free anyway: hand back an empty tree rather
    // than diverging if that invariant is ever wrong.
    let root = push_box(&mut boxes, None, BoxKind::AnonymousBlock, LayoutStyle::initial(), Vec::new());
    BoxTree { boxes, root }
}

/// Whether a container element's own box is block- or inline-level, per its (already-folded)
/// computed `display`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum ContainerKind {
    Block,
    Inline,
}

/// One frame of the explicit stack [`build`] walks with instead of recursion: an
/// element whose box is not yet finalized because its children are still being visited.
struct Frame {
    node: NodeId,
    style: LayoutStyle,
    kind: ContainerKind,
    /// This frame's DOM children, snapshotted up front so the walk does not need to hold a
    /// live `Children` iterator (borrowed from `document`) across pushing further frames.
    children: Vec<NodeId>,
    /// Index into `children` of the next child to classify.
    next_child: usize,
    /// Finished child `BoxId`s, in order, before the mixed-inline-run wrap pass.
    built: Vec<BoxId>,
}

/// What one DOM child becomes in the box tree, decided without yet building anything for it.
enum ChildBox {
    /// `display: none`, or a node kind that never generates a box (comment, doctype,
    /// processing instruction, nested document/fragment node, or an element with no computed
    /// style — see [`classify_child`]'s docs for when that last case arises).
    Skip,
    /// A box with no children of its own to visit: `InlineText` or `LineBreak`.
    Leaf(BoxKind, LayoutStyle),
    /// A box whose children must be visited before it can be finalized: `Block` or `Inline`.
    Container(ContainerKind, LayoutStyle),
}

/// Classifies one DOM node as a box-tree child, given `parent_style` — the style of the
/// container it would be a child of, which a text box inherits directly (a text node has no
/// computed values of its own in stylo; see
/// [`cl_style::StyledDocument::computed`]'s docs).
///
/// An element with no computed style ([`cl_style::StyledDocument::computed`] returning `None`)
/// is skipped defensively rather than guessed at: in practice this cannot happen for a child
/// [`build`] actually visits (a `display: none` ancestor is skipped before its children are
/// ever classified, and every other reached element is styled), but a hand-assembled
/// [`StyledDocument`] is not required to uphold that, and there is no sound default `display`
/// to fall back to.
fn classify_child(doc: &StyledDocument, node: NodeId, parent_style: &LayoutStyle) -> ChildBox {
    let document = doc.document();
    let Some(dom_node) = document.get(node) else {
        return ChildBox::Skip;
    };

    match &dom_node.kind {
        NodeKind::Text(_) => ChildBox::Leaf(BoxKind::InlineText(node), parent_style.clone()),
        NodeKind::Element(element) => {
            let Some(cv) = doc.computed(node) else {
                return ChildBox::Skip;
            };
            let style = adapt(cv);
            if style.display == Display::None {
                return ChildBox::Skip;
            }
            if element.name.local == local_name!("br") {
                return ChildBox::Leaf(BoxKind::LineBreak, style);
            }
            match style.display {
                Display::Block => ChildBox::Container(ContainerKind::Block, style),
                // `Display::None` was already handled above.
                Display::Inline | Display::None => {
                    ChildBox::Container(ContainerKind::Inline, style)
                }
            }
        }
        NodeKind::Document
        | NodeKind::Doctype(_)
        | NodeKind::Comment(_)
        | NodeKind::ProcessingInstruction { .. }
        | NodeKind::DocumentFragment => ChildBox::Skip,
    }
}

/// A container element's own display → [`ContainerKind`] (already folded onto block/inline
/// by [`crate::style_adapt::adapt`]; `Display::None` never reaches this — the root box is
/// only built after confirming the root element itself is not `display: none`... actually it
/// is not filtered — see [`build`]).
fn container_kind(style: &LayoutStyle) -> ContainerKind {
    match style.display {
        Display::Inline => ContainerKind::Inline,
        Display::Block | Display::None => ContainerKind::Block,
    }
}

/// The document element: the first element child of the document node. `None` for a document
/// with no element at all.
fn root_element(document: &Document) -> Option<NodeId> {
    document
        .children(document.root())
        .find(|id| document.element(*id).is_some())
}

/// Appends a new box to `boxes` and returns its id.
fn push_box(
    boxes: &mut Vec<LayoutBox>,
    node: Option<NodeId>,
    kind: BoxKind,
    style: LayoutStyle,
    children: Vec<BoxId>,
) -> BoxId {
    let id = BoxId::from_index(boxes.len());
    boxes.push(LayoutBox {
        node,
        kind,
        style,
        children,
    });
    id
}

/// Whether a box is block-level for the purposes of the mixed-children wrap rule.
fn is_block_level(kind: &BoxKind) -> bool {
    matches!(kind, BoxKind::Block | BoxKind::AnonymousBlock)
}

/// Applies CSS 2.1 §9.2.1.1's anonymous-block-wrapping rule to one container's already-built
/// children: if `built` mixes block-level and inline-level boxes, each maximal run of
/// inline-level boxes is replaced by a single new `AnonymousBlock` box wrapping that run
/// (styled per [`LayoutStyle::anonymous_block`], inheriting from `container_style`). If
/// `built` is homogeneous (all block-level, or all inline-level, including the empty case),
/// it is returned unchanged — an inline formatting context needs no anonymous wrapper.
fn wrap_inline_runs(
    boxes: &mut Vec<LayoutBox>,
    built: Vec<BoxId>,
    container_style: &LayoutStyle,
) -> Vec<BoxId> {
    let has_block = built
        .iter()
        .filter_map(|&id| boxes.get(id.index()))
        .any(|b| is_block_level(&b.kind));
    let has_inline = built
        .iter()
        .filter_map(|&id| boxes.get(id.index()))
        .any(|b| !is_block_level(&b.kind));
    if !(has_block && has_inline) {
        return built;
    }

    let mut result = Vec::with_capacity(built.len());
    let mut run: Vec<BoxId> = Vec::new();
    for id in built {
        let block_level = boxes.get(id.index()).is_some_and(|b| is_block_level(&b.kind));
        if block_level {
            if !run.is_empty() {
                result.push(flush_run(boxes, std::mem::take(&mut run), container_style));
            }
            result.push(id);
        } else {
            run.push(id);
        }
    }
    if !run.is_empty() {
        result.push(flush_run(boxes, run, container_style));
    }
    result
}

/// Wraps one maximal run of inline-level children in a fresh `AnonymousBlock` box.
fn flush_run(boxes: &mut Vec<LayoutBox>, run: Vec<BoxId>, container_style: &LayoutStyle) -> BoxId {
    let style = LayoutStyle::anonymous_block(container_style);
    push_box(boxes, None, BoxKind::AnonymousBlock, style, run)
}
