[package]
name = "cl-fuzz"
version = "0.0.0"
publish = false
edition = "2024"
license = "Apache-2.0 OR MIT"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
cl-ipc = { path = "../../crates/ipc" }

[[bin]]
name = "ipc_decode"
path = "fuzz_targets/ipc_decode.rs"
test = false
doc = false
bench = false

[workspace]
